name: CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    # ✅ Install Chrome
    - name: Install Chrome
      run: choco install googlechrome --no-progress --yes

    # 🔍 Debug Chrome + ChromeDriver
    - name: Check Chrome Version
      run: |
        if (Get-Command chrome.exe -ErrorAction SilentlyContinue) { chrome.exe --version } else { echo "Chrome.exe not in PATH" }
        if (Get-Command chromedriver.exe -ErrorAction SilentlyContinue) { chromedriver.exe --version } else { echo "Chromedriver.exe not in PATH" }

    # ✅ Run Maven with safer TLS handling
    - name: Build and Test with Maven
      run: mvn -Dmaven.wagon.http.pool=false -B clean test --file pom.xml

    - name: Upload JUnit Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: junit-test-results
        path: target/surefire-reports/TEST-*.xml

    - name: Upload Extent Reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: extent-reports
        path: TestResults

    - name: Upload TestNG Reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: testng-reports
        path: test-output
